### ISSUE TITLE
Shorter YAML arrays

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [codebrawl/arnold#5]
When using `Arnold#edit` on a Mongoid model, the YAMLized version of the document looks like this:

```

---
_id: !ruby/object:BSON::ObjectId
  data:
  - 77
  - 255
  - 186
  - 158
  - 155
  - 230
  - 84
  - 12
  - 77
  - 0
  - 0
  - 1
email: jeff@kreeftmeijer.nl
github_id: 46321
login: jeffkreeftmeijer
name: Jeff Kreeftmeijer
nickname: jeffkreeftmeijer
token: 86b64b55edc4da8bb7f6b9c7272551402bfd13c1
urls:
  GitHub: http://github.com/jeffkreeftmeijer
  Blog: http://jeffkreeftmeijer.com
participations: []
average_score: 0.0
```

As you can see, the `_id` field in Mongoid is an array internally, which means YAML takes fifteen lines to show it. We've decided not to show all fields in #2, but since there will be an option to show these fields, we might need to build something in to handle this specific case. If I remember correctly, this would be valid YAML too:

```

---
_id: !ruby/object:BSON::ObjectId
  data: [77, 255, 186, 158, 155, 230, 84, 12, 77, 0, 0, 1]
email: jeff@kreeftmeijer.nl
github_id: 46321
login: jeffkreeftmeijer
name: Jeff Kreeftmeijer
nickname: jeffkreeftmeijer
token: 86b64b55edc4da8bb7f6b9c7272551402bfd13c1
urls:
  GitHub: http://github.com/jeffkreeftmeijer
  Blog: http://jeffkreeftmeijer.com
participations: []
average_score: 0.0
```

It would be awesome if we could get YAML to do that for any array field that doesn't contain arrays or hashes. :)
